/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ladn.carsharingclub.ing1.view;

import fr.ladn.carsharingclub.ing1.model.Reparation;
import fr.ladn.carsharingclub.ing1.sockets.Client;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.*;
import org.apache.log4j.Logger;
/**
 *
 * @author kahel
 */
public class Monitor extends javax.swing.JPanel {
    
    ArrayList<String> liste_statut;
    private Client client;
    private final static Logger logger = Logger.getLogger(Monitor.class.getName());
    /**
     * Creates new form Monitor
     */
    public Monitor(Client client){
               this.client=client;
               initComponents();
               liste_statut=new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jCheckBox1.setText("Diagnostiqué");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("En cours de réparation");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("En suspend");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("Réparer");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Filtrer par statut (cochez ci-dessous) : ");

        jLabel2.setText("AFFICHER LES OPERATION SUR LES VEHICULES ACTUELLEMENT DANS LE DEPOT");

        jButton1.setText("Afficher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox4)
                            .addComponent(jLabel1)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jButton1)))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox4)
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addContainerGap(274, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        liste_statut.add("diagnostique");     
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        liste_statut.add("en cours");
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
        liste_statut.add("en suspend");
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        liste_statut.add("reparer");
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try {
                 
             
                    String[] tableHeader = {"id_reparation","statut","priorite","date entree","date sortie","id technicien","id vehicule","id panne","id place"};

                     JFrame fenetre = new JFrame();

                   
                        fenetre.setTitle("Operation en cours");
                        ArrayList<Reparation> reparations = client.getOperationsStatus(liste_statut);
                        Object[][] donnees = new Object[reparations.size()][tableHeader.length];
                        for (int i = 0; i < reparations.size(); i++) {
                            donnees[i][0] = reparations.get(i).getId_reparation();
                            donnees[i][1] = reparations.get(i).getStatut_reparation();
                            donnees[i][2] = reparations.get(i).getPriorite();
                            donnees[i][3] = reparations.get(i).getDate_entrée_vehicule();
                            donnees[i][4] = reparations.get(i).getDate_sortie();
                            donnees[i][5] = reparations.get(i).getId_technicien();
                            donnees[i][6] = reparations.get(i).getId_vehicule();
                            donnees[i][7] = reparations.get(i).getId_panne();
                            donnees[i][8] = reparations.get(i).getId_place();
                            
                        }
                        JTable tableau = new JTable(donnees, tableHeader);
                        JScrollPane menuder = new JScrollPane(tableau);
                        fenetre.getContentPane().add(tableau.getTableHeader(), BorderLayout.NORTH);
                        fenetre.getContentPane().add(menuder, BorderLayout.CENTER);
                        fenetre.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        fenetre.pack();
                        if (donnees.length == 0) JOptionPane.showMessageDialog(null, "Il n'y a pas d'operations correspondant à vos criteres");
                        fenetre.setVisible(true);
                   
                } catch (Exception err) {
                    JOptionPane.showMessageDialog(null, "erreur lors de la lecture des operations.");
                    logger.error("Failed to read part. Exception: " + err.getMessage());
                }
            

        
  

        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
