/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.ladn.carsharingclub.ing1.view;

import fr.ladn.carsharingclub.ing1.model.WorkFlowRep;
import fr.ladn.carsharingclub.ing1.sockets.Client;
import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import org.apache.log4j.Logger;

/**
 *
 * @author kahel
 */
public class StatistiqueView extends javax.swing.JPanel {
    private Client client;
    private final static Logger logger = Logger.getLogger(MonitorView.class.getName());
    private ArrayList<WorkFlowRep> stats=new ArrayList<>();

    /**
     * Creates new form StatView
     */
    public StatistiqueView(Client c) {
        this.client=c;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        jLabel1.setText("Choisissez le :  ");

        jLabel2.setText("Statistiques Manutentionnaire");

        jRadioButton1.setText("Nombre de véhicule par technicien (365 dernier jour)");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Nombre de véhicule par jour, par statut");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jRadioButton3.setText("Nombre de véhicule par statut");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Afficher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jRadioButton4.setText("Nombre de vehicule réparé par technicien dans la journée ");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton1, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(jButton1)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1))
                .addGap(10, 10, 10)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton3)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton4)
                .addGap(45, 45, 45)
                .addComponent(jButton1)
                .addContainerGap(100, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
         jRadioButton1.setSelected(false);
         jRadioButton3.setSelected(false);
         jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
         jRadioButton2.setSelected(false);
         jRadioButton1.setSelected(false);
         jRadioButton4.setSelected(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        stats.clear();
        if(jRadioButton1.isSelected()) {
            stats.addAll(client.getCalculStat(1));
            try {
                        String[] tableHeader = {"id_technicien","nom","nombre de vehicule"};

                        JFrame fenetre = new JFrame();

                        fenetre.setTitle("Nombre de vehicule par technicien sur 365 jours");
                        Object[][] donnees = new Object[stats.size()][tableHeader.length];
                        for (int i = 0; i < stats.size(); i++) {
                            donnees[i][0] = stats.get(i).getId_tech();
                            donnees[i][1] = stats.get(i).getNom_tech();
                            donnees[i][2] = stats.get(i).getCount();    
                        }
                        JTable tableau = new JTable(donnees, tableHeader);
                        JScrollPane menuder = new JScrollPane(tableau);
                        fenetre.getContentPane().add(tableau.getTableHeader(), BorderLayout.NORTH);
                        fenetre.getContentPane().add(menuder, BorderLayout.CENTER);
                        fenetre.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        fenetre.pack();
                        if (donnees.length == 0) JOptionPane.showMessageDialog(null, "Il n'y a pas de stats correspondant à  vos criteres");
                        fenetre.setVisible(true);
                } catch (Exception err) {
                    JOptionPane.showMessageDialog(null, "erreur lors de la lecture des stats.");
                    logger.error("Failed to read stats. Exception: " + err.getMessage());
                }
        }
        if(jRadioButton2.isSelected()) {
            stats.addAll(client.getCalculStat(3));
             try {
                        String[] tableHeader = {"Date","Statut","Nombre de vehicule"};

                        JFrame fenetre = new JFrame();

                        fenetre.setTitle("Nombre d'entree de vehicule par jour et par statut");
                        Object[][] donnees = new Object[stats.size()][tableHeader.length];
                        for (int i = 0; i < stats.size(); i++) {
                            donnees[i][0] = stats.get(i).getDateStat(); 
                            donnees[i][1] = stats.get(i).getStatut(); 
                            donnees[i][2] = stats.get(i).getCount();    
                        }
                        JTable tableau = new JTable(donnees, tableHeader);
                        JScrollPane menuder = new JScrollPane(tableau);
                        fenetre.getContentPane().add(tableau.getTableHeader(), BorderLayout.NORTH);
                        fenetre.getContentPane().add(menuder, BorderLayout.CENTER);
                        fenetre.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        fenetre.pack();
                        if (donnees.length == 0) JOptionPane.showMessageDialog(null, "Il n'y a pas de stats correspondant à  vos criteres");
                        fenetre.setVisible(true);
                } catch (Exception err) {
                    JOptionPane.showMessageDialog(null, "erreur lors de la lecture des stats.");
                    logger.error("Failed to read stats. Exception: " + err.getMessage());
                }
        }
        if(jRadioButton3.isSelected()) {
            stats.addAll(client.getCalculStat(2));
            try {
                        String[] tableHeader = {"Statut","nombre de vehicule"};

                        JFrame fenetre = new JFrame();

                        fenetre.setTitle("Nombre de vehicule par statut actuellement dans le depot");
                        Object[][] donnees = new Object[stats.size()][tableHeader.length];
                        for (int i = 0; i < stats.size(); i++) {
                            donnees[i][0] = stats.get(i).getNom_tech(); 
                            donnees[i][1] = stats.get(i).getCount();    
                        }
                        JTable tableau = new JTable(donnees, tableHeader);
                        JScrollPane menuder = new JScrollPane(tableau);
                        fenetre.getContentPane().add(tableau.getTableHeader(), BorderLayout.NORTH);
                        fenetre.getContentPane().add(menuder, BorderLayout.CENTER);
                        fenetre.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        fenetre.pack();
                        if (donnees.length == 0) JOptionPane.showMessageDialog(null, "Il n'y a pas de stats correspondant à  vos criteres");
                        fenetre.setVisible(true);
                } catch (Exception err) {
                    JOptionPane.showMessageDialog(null, "erreur lors de la lecture des stats.");
                    logger.error("Failed to read stats. Exception: " + err.getMessage());
                }

        }
        if(jRadioButton4.isSelected()) {
            stats.addAll(client.getCalculStat(4));
            try {
                        String[] tableHeader = {"id_technicien","nom","nombre de vehicule"};

                        JFrame fenetre = new JFrame();

                        fenetre.setTitle("Nombre de vehicule réparé par technicien dans la journée");
                        Object[][] donnees = new Object[stats.size()][tableHeader.length];
                        for (int i = 0; i < stats.size(); i++) {
                            donnees[i][0] = stats.get(i).getId_tech();
                            donnees[i][1] = stats.get(i).getNom_tech();
                            donnees[i][2] = stats.get(i).getCount();    
                        }
                        JTable tableau = new JTable(donnees, tableHeader);
                        JScrollPane menuder = new JScrollPane(tableau);
                        fenetre.getContentPane().add(tableau.getTableHeader(), BorderLayout.NORTH);
                        fenetre.getContentPane().add(menuder, BorderLayout.CENTER);
                        fenetre.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                        fenetre.pack();
                        if (donnees.length == 0) JOptionPane.showMessageDialog(null, "Il n'y a pas de stats correspondant à  vos criteres");
                        fenetre.setVisible(true);
                } catch (Exception err) {
                    JOptionPane.showMessageDialog(null, "erreur lors de la lecture des stats.");
                    logger.error("Failed to read stats. Exception: " + err.getMessage());
                }
        }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        jRadioButton2.setSelected(false);
        jRadioButton3.setSelected(false);
        jRadioButton1.setSelected(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
